version: "3.9"

services:
  db:
    image: postgres:15.2-alpine
    volumes:
    - ./database:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      - POSTGRES_DB=movies
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=secret