name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up dotnet
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: '7.0'
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build project
      run: dotnet build
      
    - name: Test project
      env: 
        CONNECTION_STRING: ConnectionStrings:Server=${{ secrets.MSSQL_HOST }};Database=photos;User Id=${{ secrets.MSSQL_USER }};Password=${{ secrets.MSSQL_PASSWORD }};
      run: dotnet test --environment "CONNECTION_STRING"

    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build image and push
      env:
        REGISTRY: ${{ secrets.DOCKER_USERNAME }}
        REPOSITORY: photoapi
        IMAGE_TAG: latest
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        
 
